# Generated by Django 5.1 on 2024-09-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadidato',
            new_name='Candidato',
        ),
    ]
