# Generated by Django 5.1 on 2024-09-25 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_cadidato_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='img_nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
