# Generated by Django 5.1 on 2024-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_candidato_img_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='img_nome',
            field=models.CharField(default='candidato_3.jpg', max_length=50),
        ),
    ]
