# Generated by Django 5.1 on 2024-09-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_candidato_img_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='img_nome',
        ),
        migrations.AddField(
            model_name='candidato',
            name='cargo',
            field=models.CharField(choices=[('Vereador', 'vereador'), ('Prefeito', 'prefeito')], default='Vereador', max_length=20),
        ),
        migrations.AddField(
            model_name='candidato',
            name='imagem',
            field=models.ImageField(default='candidato_1.jpg', upload_to='profile'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='partido',
            field=models.CharField(choices=[('Partido Marvel Comics', 'PMC'), ('Partido Detective Comics', 'PDC')], default='PMC', max_length=24),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='votos',
            field=models.BigIntegerField(default=0, verbose_name='votos'),
        ),
    ]
