# Generated by Django 5.1 on 2024-09-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_candidato_img_nome_candidato_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='partido',
            field=models.CharField(choices=[('PMC', 'Partido Marvel Comics'), ('PDC', 'Partido Detective Comics')], default='PMC', max_length=24),
        ),
    ]
