# Generated by Django 5.1 on 2024-09-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_candidato_partido'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='apelido',
            field=models.CharField(default='Apelido', max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='proposta',
            field=models.CharField(default='Proposta', max_length=200),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cargo',
            field=models.CharField(choices=[('Vereador', 'vereador'), ('Prefeito', 'prefeito'), ('Vice-Prefeito', 'vice-prefeito')], default='Vereador', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(default='Nome', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='partido',
            field=models.CharField(choices=[('PMC', 'Partido Marvel Comics'), ('PDC', 'Partido Detective Comics'), ('Branco', 'branco')], default='Branco', max_length=50),
        ),
    ]
