# Generated by Django 5.1 on 2024-09-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_candidato_apelido_candidato_proposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cargo',
            field=models.CharField(choices=[('vereador', 'Vereador'), ('prefeito', 'Prefeito'), ('vice-prefeito', 'Vice-Prefeito')], default='vereador', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='proposta',
            field=models.TextField(default='Proposta', max_length=300),
        ),
    ]
