# Generated by Django 5.1 on 2024-09-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_candidato_cargo_alter_candidato_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='proposta',
            field=models.TextField(default='Proposta', max_length=400),
        ),
    ]
